### PR TITLE
getImage helper function based on item name

### PR DESCRIPTION
**Pull request by BaReinhard**
Created a node js helper library to find images based on items name

### CODE REVIEW

**Comment by GreenDude120** [comment]
are u suggesting running nodejs? because we are trying not to. we dont wanna run anything. twitch has front end and we already have a web api on realm. so we wanna cut out the middleman node js server we have atm.

**Comment by BaReinhard** [comment]
Sorry it was my understanding that this would be a twitch extension.

**Comment by GreenDude120** [comment]
It is. but a twitch extension does not need node js. We upload front end to twitch and it gets the requested character data from the realm's web api.

**Comment by BaReinhard** [comment]
This actually won’t work due to how assets are loaded in the twitch extension. The dependency fs isn’t portable to browser like environments and causes the helper function to not work. I will take another look how the current trade portal is doing images and use a similar scheme as it will be easier to just update assets from one location and use it from there anyway.

**Pull request closed without merging**
